services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/oskarbarcz/symfony-project-bootstrap:app-${VERSION:-3.0.0}
    environment:
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      DATABASE_URL: "postgresql://user:password@database:3306/symfony-bootstrap"
  database:
     image: 'postgres:16'
     environment:
      POSTGRES_DB: "symfony-bootstrap"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
