framework:
  cache:
    pools:
      product_cache:
        adapter: cache.adapter.redis
        default_lifetime: 3600
        provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DATABASE_PRODUCT)%'

      report_cache:
        adapter: cache.adapter.redis
        default_lifetime: 3600
        provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DATABASE_REPORT)%'
