security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    dev_user_provider:
      memory:
        users:
          dev_user:
            password: 'password'
            roles: [ 'ROLE_USER' ]

  firewalls:
    dev_api:
      pattern: ^/api
      stateless: true
      provider: dev_user_provider
      jwt: ~

#  access_control:
#    - { path: ^/api, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10

